package vn.btl.hdvcoreservice.utils;

import lombok.Builder;
import lombok.Data;

@Data
@Builder
public class Operator {
    public enum ACTION {

        VIEW_LIST_CUSTOMER, VIEW_CUSTOMER_DETAIL,CREATE_CUSTOMER, DELETE_CUSTOMER, UPDATE_CUSTOMER,
        VIEW_CATEGORY, CREATE_CATEGORY, DELETE_CATEGORY, UPDATE_CATEGORY,
        VIEW_PRODUCT, CREATE_PRODUCT, UPDATE_PRODUCT, DELETE_PRODUCT,

        CREATE_ODER, VIEW_ORDER, VIEW_ORDER_DETAIL, UPDATE_ORDER_STATUS, DELETE_ORDER, UPDATE_ORDER,

        CREATE_SHIPPER, VIEW_SHIPPER, UPDATE_SHIPPER, DELETE_SHIPPER,
        CREATE_SUPPLIER, VIEW_SUPPLIER, UPDATE_SUPPLIER, DELETE_SUPPLIER,

        CREATE_USER_ROLE, VIEW_USER_ROLE, UPDATE_USER_ROLE, DELETE_USER_ROLE,
        CREATE_BILLING,
        VIEW_REPORT
    }

    protected ACTION action;

}
